### PR TITLE
Support for custom Adhan and Fajr adhan

### PR DESCRIPTION
**Pull request by akhandok**
This PR proposes to add support for choosing a custom Adhan audio file to play. The PR also includes changes to play a different Adhan at Fajr that includes recitations specific for the Fajr Adhan.

### CODE REVIEW

**Comment by akhandok** [comment]
The audio file I chose for Fajr is just one I picked out that I liked. Please let me know if you would like to change, or feel free to edit the PR.

**Comment by akhandok** [comment]
Please note that testing was very rough. I am not able to install Docker because I have Windows 10 Home, so all my testing was done in place via Google Chrome's Developer Tools.

**Comment by meezaan** [comment]
Thank you @akhandok. I will test this soon, God willing.

**Comment by akhandok** [comment]
Hello @meezaan : I closed this PR and opened #16 because this PR has an incorrect author associated with the commits. Please retire this PR in favor of the new one. Thank you.

**Comment by meezaan** [comment]
Will do @akhandok , thank you.

**Pull request closed without merging**
